version: "3"
services:
  backend:
    image: ghcr.io/fernandoglatz/openai-compatible-proxy:latest
    hostname: backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    depends_on:
      - mongo
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  mongo:
    image: mongo:7
    hostname: mongo
    ports:
     - "27017:27017"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - mongodb-data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  redis:
    image: redis:7-alpine
    hostname: redis
    ports:
     - "0.0.0.0:6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  mqtt:
    image: eclipse-mosquitto:2
    hostname: mqtt
    ports:
     - "1883:1883"
     - "9001:9001"
    volumes:
      - mqtt-data:/mosquitto/data
      - mqtt-logs:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  mongodb-data:
  redis-data:
  mqtt-data:
  mqtt-logs:
