version: "3"
services:
  backend:
    # Multi-arch image (supports linux/amd64 and linux/arm64)
    image: ghcr.io/fernandoglatz/openai-compatible-proxy:latest
    hostname: backend
    ports:
      - "8080:8080"
    #network_mode: "host"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ./conf:/app/conf
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  mongo:
    image: mongo:7
    hostname: mongo
    ports:
     - "27017:27017"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - mongodb-data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  mongodb-data:
