server:
  listening: "0.0.0.0:8080"
  context-path: "/"

data:
  mongo:
    uri: "mongodb://mongo:27017"
    database: "openai-compatible-proxy"

lm-studio:
  url: "http://127.0.0.1:11434"
  timeout: 600s
  wol:
    enabled: true
    mac-address: "00:00:00:00:00:00"
    broadcast-address: "255.255.255.255:9"
    max-retries: 10
    retry-wait: 5s

mqtt:
  enabled: true
  broker: "tcp://mqtt:1883"
  client-id: "openai-compatible-proxy"
  username: "guest"
  password: "guest"
  topic: "system/suspend"
  qos: 1
  idle:
    timeout: 10m
    message: "suspend"

log:
  level: TRACE
  format: TEXT
  colored: true
